export const NUTRIENTS: Record<string, { label: string; unit: string; dailyValue: number }> = {
  calories: { label: 'Calories', unit: 'kcal', dailyValue: 2000 },
  fat_g: { label: 'Total Fat', unit: 'g', dailyValue: 78 },
  saturated_fat_g: { label: 'Saturated Fat', unit: 'g', dailyValue: 20 },
  trans_fat_g: { label: 'Trans Fat', unit: 'g', dailyValue: 0 },
  monounsaturated_fat_g: { label: 'Monounsaturated Fat', unit: 'g', dailyValue: 0 },
  polyunsaturated_fat_g: { label: 'Polyunsaturated Fat', unit: 'g', dailyValue: 0 },
  cholesterol_mg: { label: 'Cholesterol', unit: 'mg', dailyValue: 300 },
  sodium_mg: { label: 'Sodium', unit: 'mg', dailyValue: 2300 },
  carbs_g: { label: 'Total Carbohydrates', unit: 'g', dailyValue: 275 },
  fiber_g: { label: 'Dietary Fiber', unit: 'g', dailyValue: 28 },
  sugar_g: { label: 'Total Sugars', unit: 'g', dailyValue: 0 },
  added_sugar_g: { label: 'Added Sugars', unit: 'g', dailyValue: 50 },
  protein_g: { label: 'Protein', unit: 'g', dailyValue: 50 },
  vitamin_a_mcg: { label: 'Vitamin A', unit: 'mcg', dailyValue: 900 },
  vitamin_c_mg: { label: 'Vitamin C', unit: 'mg', dailyValue: 90 },
  vitamin_d_mcg: { label: 'Vitamin D', unit: 'mcg', dailyValue: 20 },
  vitamin_e_mg: { label: 'Vitamin E', unit: 'mg', dailyValue: 15 },
  vitamin_k_mcg: { label: 'Vitamin K', unit: 'mcg', dailyValue: 120 },
  thiamin_mg: { label: 'Thiamin (B1)', unit: 'mg', dailyValue: 1.2 },
  riboflavin_mg: { label: 'Riboflavin (B2)', unit: 'mg', dailyValue: 1.3 },
  niacin_mg: { label: 'Niacin (B3)', unit: 'mg', dailyValue: 16 },
  vitamin_b6_mg: { label: 'Vitamin B6', unit: 'mg', dailyValue: 1.7 },
  folate_mcg: { label: 'Folate', unit: 'mcg', dailyValue: 400 },
  vitamin_b12_mcg: { label: 'Vitamin B12', unit: 'mcg', dailyValue: 2.4 },
  calcium_mg: { label: 'Calcium', unit: 'mg', dailyValue: 1300 },
  iron_mg: { label: 'Iron', unit: 'mg', dailyValue: 18 },
  magnesium_mg: { label: 'Magnesium', unit: 'mg', dailyValue: 420 },
  phosphorus_mg: { label: 'Phosphorus', unit: 'mg', dailyValue: 1250 },
  potassium_mg: { label: 'Potassium', unit: 'mg', dailyValue: 4700 },
  zinc_mg: { label: 'Zinc', unit: 'mg', dailyValue: 11 },
  copper_mg: { label: 'Copper', unit: 'mg', dailyValue: 0.9 },
  manganese_mg: { label: 'Manganese', unit: 'mg', dailyValue: 2.3 },
  selenium_mcg: { label: 'Selenium', unit: 'mcg', dailyValue: 55 },
};
